### ISSUE TITLE
Check results error on CRAN old release

### ISSUE THREAD

**Issue by smjenness** [statnet/statnet.common#1]
@krivit I'm sure you've seen this, but in case not:
https://www.r-project.org/nosvn/R.check/r-oldrel-osx-x86_64/statnet.common-00check.html

It results in an error in all the depending packages, including ergm, tergm, and EpiModel...

**Comment by martinamorris** [comment]
> @krivit I'm sure you've seen this, but in case not:
> https://www.r-project.org/nosvn/R.check/r-oldrel-osx-x86_64/statnet.common-00check.html

as Pavel noted, this is b/c we have been requiring R > 3.0 up till now, 
and that causes problems for this one OS.  Carter, for example, isn't fond 
of updating R as that tends to break lots of things for him.  but at this 
point we need to take the leap, so Pavel will be changing this in the next 
release of ergm etc.

**Comment by doorisajar** [comment]
Is there any more detail somewhere on what the effect of this issue was? I'm in an AWS environment where for various reason I can't yet update to R 3.5, but I have a dependency on this package and am trying to figure out if I can get away with using an older version.

**Comment by krivit** [comment]
The best idea I have at this point is downloading the source code for `statnet.common`, changing the required R version, and installing it from source.

**Comment by doorisajar** [comment]
I've been using the old version for now, but tried cloning and building as a test. Some of the examples fail, e.g.:

```
data(line, package="coda")
colMeans.mcmc.list(line)[c(2,3,1)]
colMeans.mcmc.list(lapply.mcmc.list(line, `[`,,c(2,3,1)))
```

```
 Error in NextMethod("[") : argument is missing, with no default 
```

Fortunately, this doesn't affect me, so I'm just using my modified build with R 3.4 until Amazon updates the available R version.
