### ISSUE TITLE
Allow and handle list input for control= arguments.

### ISSUE THREAD

**Issue by krivit** [statnet/statnet.common#12]
This issue applies to most Statnet packages, so the back-end will need to be implemented here.

A major complaint of the more sophisticated users is that typing out `control.*()` is unnecessarily verbose, particularly for functions such as `ergm.ego()`, where there is a potential for three levels of controls:
```r
ergm.ego(...,
  control = control.ergm.ego(...,
    ergm.control = control.ergm(...,
      SAN.control = control.SAN(...)
    )
  )
)
```
One quick way to simplify this would be to teach the functions to pass `list`s (as opposed to `control.list`s) through `control.*()` for the appropriate function, i.e.,
```r
ergm.ego(...,
  control = list(...,
    ergm.control = list(...,
      SAN.control = list(...)
    )
  )
)
```
or, even more briefly,
```r
ergm.ego(...,
  control = list(...,
    ergm = list(...,
      SAN = list(...)
    )
  )
)
```
This should be possible to implement by calling something along the lines of `do.call(control.ergm.ego, control)` to catch spelling errors and preprocess arguments. One potential problem is that some arguments might be defaults of others, or functions thereof.  For example, right now, in `control.ergm()`, `SAN.control=` argument inherits a whole bunch of arguments from MCMC, which might be implementable by first evaluating the outer control lists, then the inner ones in the environment of the outer.

Another proposal was to teach `ergm.ego()` to understand "flattened" lists, such as
```r
ergm.ego(...,
  control = list(
    ergm.ego = list(...),
    ergm = list(...),
    SAN = list(...)
  )
)
```
This requires `ergm.ego()` to be aware of the control sublists.

@drh20drh20 , @sgoodreau , @martinamorris , @chad-klumb , I'm creating this issue here to follow up on our discussion.

**Comment by krivit** [comment]
Regarding the potential problem with inheriting arguments, we might make handling of list sub-arguments the responsibility of its respective control function. I think that would work.

**Comment by mbojan** [comment]
I think flattening sounds attractive. This would address the clobbering issue as in https://github.com/krivit/ergm.ego-papers/issues/46, wouldn't it? At the same time, perhaps keeping a dedicated class and function instead of raw lists might allow for more clever handling of dependent control options such as `ppopsize` and `ppopsize.mult` in `control.ergm.ego()`.

**Comment by mbojan** [comment]
Is there actually any disadvantage to have the control options as a completely flat list, just like `options()`?

**Comment by krivit** [comment]
Idea:

1. Grab the `control=` argument as a whole (without evaluating).
2. Substitute the appropriate `control.*` functions in place of `list`.
3. Evaluate.

**Comment by krivit** [comment]
Update: I had misunderstood R's calling semantics. For example, for a function `f <- function(a=1, b=a+1) c(a=a,b=b)`, it's legal to call it with just `a`, i.e., `f(1)` to get a vector `c(1,2)`, but you can't call `f(1,a+2)`: it'll look for `a` in the caller's environment. This actually simplifies the problem, since we don't need to lazy-evaluate anything.

**Comment by krivit** [comment]
Finally got this to work. The construct
```r
ergm.ego(...,
  control = list(...,
    ergm.control = list(...,
      SAN.control = list(...)
    )
  )
)
```
should now work seamlessly. It piggybacks on `check.control.class()`, so no modifications to the client packages (`ergm`, `ergm.ego`, etc.) should be required.

Renaming argument names (e.g., `ergm=` instead of `ergm.control=`) requires making trivial changes to the relevant `control.*()` functions. Unnesting them requires more extensive changes to the underlying functions (`ergm()`, `ergm.ego()`, etc.).

@martinamorris , @drh20drh20 , @chad-klumb , what do you think?

**Comment by martinamorris** [comment]
simple clear arguments, yay!  nesting ... let's see.

getting back to the use case that triggered this what are the implications for:

```
fit <- ergm.ego(nsfg.obj_c ~ terms + offset(sex, concurrent),
                 control = control.ergm.ego(
		ergm.control = control.ergm(MCMC.prop.args = list(attr = "race", adaptive = TRUE), 
                                                                                       MCMC.prop.weights = "StratTNT", 
                                                                                        SAN.control = control.san(SAN.prop.args = list(
								bound = 1, 
								attr = "sex", 
								fmat = matrix(c(1,0,0,1), 2, 2)),
 								SAN.prop.weights = "BDTNT"))))
```

**Comment by krivit** [comment]
If we rename the arguments, it would be along the lines of:
```r
fit <- ergm.ego(nsfg.obj_c ~ terms + offset(sex, concurrent),
                 control = list(
		 ergm = list(MCMC.prop.args = list(attr = "race", adaptive = TRUE), 
                                                                   MCMC.prop.weights = "StratTNT", 
                                                                   SAN = list(SAN.prop.args = list( bound = 1, 
								                                                   attr = "sex", 
								                                                   fmat = matrix(c(1,0,0,1), 2, 2)),
 								                                                   SAN.prop.weights = "BDTNT"))))
```

**Comment by krivit** [comment]
This looks like it's been resolved. The next step is #13.
