### ISSUE TITLE
Affiliation - email mapping in the wall of text

### ISSUE THREAD

**Issue by mbojan** [statnet/statnet.common#15]
Not a top priority, but: I'm using my Gmail email on GH and when signing R packages. This is not caught by `statnetStartupMessage()` when producing ppls affiliations, as the function only looks at email's domain. I'm thinking of implementing a general override of that logic, similarly to `STATNET.ORG_MAP` as it is currently. Namely a list of ppl who would like to override the domain mapping mechanism and enforce a particular affiliation.

Any thoughts @krivit ?

**Comment by krivit** [comment]
I increasingly wonder if we should just use a nonstandard `comment` field rather than try to autodetect stuff. E.g.,
```
Authors@R: c(
             person("Pavel N.", "Krivitsky", role=c("aut","cre"), email="pavel@statnet.org", comment=c(ORCID="0000-0002-9101-3362", affiliation="University of New South Wales)))
```
One question is---"affiliation" or "institution"?

**Comment by krivit** [comment]
I am going with `affil=` for now, and it overrides any e-mail-based lookup. (It's in the `startup_affil` branch.)

What do you think?

**Comment by krivit** [comment]
@mbojan , any thoughts before I merge this?

**Comment by mbojan** [comment]
> I increasingly wonder if we should just use a nonstandard `comment` field rather than try to autodetect stuff.

I agree with that. 

> I am going with `affil=` for now, and it overrides any e-mail-based lookup. (It's in the `startup_affil` branch.)

Sounds good. I actually think that, given the number of packages created by academics, perhaps `utils::person()` should have a dedicated `affiliation` argument... 


> @mbojan , any thoughts before I merge this?

Not really, go ahead.

**Comment by krivit** [comment]
@mbojan , OK, you can now make PRs to add your affiliation as needed.

**Comment by krivit** [comment]
@mbojan , or, just commit directly, I guess.
