### ISSUE TITLE
Statnet not available for R 4.3.0

### ISSUE THREAD

**Issue by emieldelange** [statnet/statnet.common#2]
I'm using RStudio 1.1.463

When trying to load 'statnet' package I get the following error:

```
Error: package or namespace load failed for ‘ergm’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 namespace ‘statnet.common’ 4.0.0 is already loaded, but >= 4.1.0 is required
Error: package ‘ergm’ could not be loaded
```

When I try to install the latest version of statnet.common directly I get the following:
```
> install_version("statnet.common", "4.2.0")
Trying https://cran.rstudio.com/
Error in download_version_url(package, version, repos, type) : 
  version '4.2.0' is invalid for package 'statnet.common'
```

**Comment by krivit** [comment]
This is working as intended. Unfortunately, there are certain bugs in `R` prior to 3.5 that `statnet.common` kept hitting, so we had to bump the minimum version. You will need to upgrade R to 3.5 or later.
