### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by keithegiles** [statnet/statnet.common#29]
An error for statnet.common is thrown when trying to install the 'network'  package into R 4.0.5. The error is pinpointed to this step:

```
[Connect] 2024/01/22 19:00:29.689159090   /opt/rstudio-connect/mnt/tmp/RtmpMXx8KV/packrat-install-c0c604c535153/statnet.common/R/matrix.utils.R:217:30: unexpected '>'
[Connect] 2024/01/22 19:00:29.689160152 216:   d <- diag(as.matrix(A))
[Connect] 2024/01/22 19:00:29.689171592 217:   d <- ifelse(d==0, 1, 1/d) |>

```
I was able to fix the issue by manually deleting the offending character and then installing the package manually.  However, this is more difficult as I'm attempting to deploy the code to a server that I don't have access to do so.

**Comment by krivit** [comment]
Next release of `statnet.common` won't use that construct, but 4.0.5 is almost 4 years old now.

**Comment by keithegiles** [comment]
4.0.5 is the version of R..not the version of statnet.common Sent from my iPhoneOn Jan 23, 2024, at 9:58 AM, Keith Giles ***@***.***> wrote:﻿I’m doing this at work, so it’s not trivial to actually update anything. Do you have any advice on how to get around this error? It pops when I try to install the package “network”Sent from my iPhoneOn Jan 22, 2024, at 9:03 PM, Pavel N. Krivitsky ***@***.***> wrote:﻿
Next release of statnet.common won't use that construct, but 4.0.5 is almost 4 years old now.

**Comment by krivit** [comment]
Yes, I was referring to the version of R: I mean 3 years old, not 4. My apologies for the confusion.

1. If you can compile packages, `install.packages("remotes"); remotes::install_github("statnet/statnet.common")` will install from this repository (which doesn't use `|>`).
2. If your admin won't update R, you can download the source and compile a recent version in your user directory.

**Comment by keithegiles** [comment]
I did install 4.1.2 in my directory, but when I deploy the app it reverts.Do you know where apt-get would put the new R so I can change the R_HOME variable to point to it?I can’t find it Sent from my iPhoneOn Jan 23, 2024, at 5:49 PM, Pavel N. Krivitsky ***@***.***> wrote:﻿
Yes, I was referring to the version of R: I mean 3 years old, not 4. My apologies for the confusion.

If you can compile packages, install.packages("remotes"); remotes::install_github("statnet/statnet.common") will install from this repository (which doesn't use |>).
If your admin won't update R, you can download the source and compile a recent version in your user directory.

**Comment by krivit** [comment]
Unfortunately, this depends on your specific IT setup, so I can't help you there. Have you tried asking your system administrator?

**Comment by keithegiles** [comment]
We got it sorted out. The issue was that the connect server was not running
4.1.2. Ugh. Sorry about all the bother.
