### ISSUE TITLE
Implement a method for comparing settings of control lists.

### ISSUE THREAD

**Issue by krivit** [statnet/statnet.common#6]
Right now, control lists can be hundreds of elements long, and there is no great way to check whether two runs have different settings.

It is thus helpful to have a method, e.g., `diff.control.list(x,y)` that goes through the entries on both lists and checks that they are identical, printing out differences if they are not. If it encounters a nested control list (e.g., `control.san` inside a `control.ergm`), it should search the differences in the sublist as well.

Since a control list's class contains information about which `control.*()` function produced it, it may also be possible to have it execute with one argument, comparing the list to its default settings.

Architecturally, the results should probably be an object of class `diff.control.list`, with an appropriate print method.

An additional method, perhaps `update.control.list()` could be implemented to "patch" one control list with the result of a `diff.control.list()`.

**Comment by krivit** [comment]
This is a follow-up on statnet/ergm#136, with a question of how to quickly identify what settings were used for an `ergm` fit.

@martinamorris , @sgoodreau , @mbojan , @chad-klumb , any thoughts?

**Comment by martinamorris** [comment]
is there a way to just capture the full text of the call, and parse it for the known arguments?

**Comment by krivit** [comment]
@martinamorris, It may be possible to substitute the formula into the call, but it wouldn't work with the control list. Anyway, that's more to do with statnet/ergm#136 than with this.

**Comment by martinamorris** [comment]
@krivit maybe I'm not understanding correctly, but if the goal is to get a quick look at the difference in the control parameters between two models, by checking the `ergm` object, then what I'm suggesting is this:

* model 1:  the call is out1 <- ergm(nw ~ terms1, control = (control.ergm(arguments1))

* model 2: the call is out2 <- ergm(nw ~ terms2, control = (control.ergm(arguments2), SAN.control = (sancontrol_args))

If you save the actual text of the entire call in a component, you can just print that out and see the differences.

**Comment by krivit** [comment]
@martinamorris , saving the call has been implemented in https://github.com/statnet/ergm/commit/1273a5f0ee7f1cf2cb546f36133df09ace40730a, based on the discussion in statnet/ergm#136. Its limitation is that if the formula and/or the control list is stored in a variable before being passed to `ergm`, it won't appear as a part of the call.

With the implementation in this ticket, you can use `diff(out1$control, out2$control)` to get the list of differences (although it'll also include the automatically updated settings).

**Comment by martinamorris** [comment]
ok, thx for the clarification, and for the changes :)  I won't close out the ticket in case you want to tie the commit to it.
