### ISSUE TITLE
LICENSE attribution clause reference nonfunctional URL

### ISSUE THREAD

**Issue by mr-c** [statnet/statnet.common#7]
Hello from Debian,

While packaging https://cran.r-project.org/package=statnet.common  we ran into some difficulty fulfilling the attribution requirements of the LICENSE file as it references a URL that does not work

    (a) you agree to retain in 'statnet.common' and any modifications to 'statnet.common'
        the copyright, author attribution and URL information as
        provided at http://statnet.org/attribution

 My guess is that this is a result of the move from statnetproject.org to statnet.org?

I found http://statnetproject.org/attribution.shtml via http://statnetproject.org/attribution/ , but it would be really better for us if one of the following occured:

1. the http://statnet.org/attribution URL worked (easy for us)
2. there was a new release where item (a) of the attribution clause was updated so that users aren't required to consult an external URL prior to redistribution (best)
3. there was a new release where the URL is restored to  http://statnetproject.org/attribution.shtml or  http://statnetproject.org/attribution

Thanks for creating, maintaining, and releasing free software and open science!

**Comment by krivit** [comment]
Hello from Statnet,

It's an honour to be packaged for Debian! We are in the process of migrating statnet.org to another server, and I think that one of the stopgap redirections has rendered that URL invalid. We are working on fixing it.

**Comment by mr-c** [comment]
:-)

Thanks for the update on option 1 (fixing the URL).

Please also consider option 2 for future releases. I think having the attribution information on your website is great, but requiring the distributor to consult a URL seems odd :-)

**Comment by martinamorris** [comment]
Will consider option 2 for the next release.  I think the reasoning behind the URL is that we maintain a suite of 10+ packages under the `statnet development team` umbrella, so the URL was a way for us to have a single place where the attribution info could be updated as needed.

**Comment by martinamorris** [comment]
Option 2 has been implemented.

**Comment by krivit** [comment]
@martinamorris , isn't it Option 1 (making statnet.org/attribution work)?
